MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  ATTRIBUTE_ON: True
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    SMOOTH_L1_BETA: 0.1111
    BOUNDARY_THRESH: 0
  ROI_HEADS:
    NAME: "AttributeRes5ROIHeads"
    NUM_CLASSES: 1600
  ROI_BOX_HEAD:
    POOLER_SAMPLING_RATIO: 2
    SMOOTH_L1_BETA: 1.
DATASETS:
  TRAIN: ("visual_genome_train", "visual_genome_val")
  TEST: ("visual_genome_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VERSION: 2
